/* Logico_Inicial: */

CREATE TABLE USUARIO (
    ID INT PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255),
    telefone VARCHAR(30),
    senha VARCHAR(30)
);

CREATE TABLE MERCADO (
    ID INT PRIMARY KEY,
    nome VARCHAR(255),
    img TEXT,
    ID_endereco INT
);

CREATE TABLE COMPRA (
    ID INT PRIMARY KEY,
    data_hora TIMESTAMP,
    stts_pgto BOOLEAN,
    frete MONEY,
    ID_usuario INT,
    ID_forma_pgto INT
);

CREATE TABLE PRODUTO (
    ID INT PRIMARY KEY,
    nome VARCHAR(255),
    img TEXT,
    ID_categoria INT
);

CREATE TABLE CATEGORIA (
    ID INT PRIMARY KEY,
    nome VARCHAR(255)
);

CREATE TABLE FORMA_PGTO (
    ID INT PRIMARY KEY,
    nome VARCHAR(255)
);

CREATE TABLE ITEM (
    ID INT PRIMARY KEY,
    preco MONEY,
    ID_mercado INT,
    ID_produto INT
);

CREATE TABLE ENDERECO (
    ID INT PRIMARY KEY,
    cidade VARCHAR(255),
    bairro VARCHAR(255)
);

CREATE TABLE compra_item (
    ID_item INT,
    ID_compra INT,
    quantidade INT
);
 
ALTER TABLE MERCADO ADD CONSTRAINT FK_MERCADO_2
    FOREIGN KEY (ID_endereco)
    REFERENCES ENDERECO (ID)
    ON DELETE RESTRICT;
 
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_2
    FOREIGN KEY (ID_usuario)
    REFERENCES USUARIO (ID)
    ON DELETE CASCADE;
 
ALTER TABLE COMPRA ADD CONSTRAINT FK_COMPRA_3
    FOREIGN KEY (ID_forma_pgto)
    REFERENCES FORMA_PGTO (ID)
    ON DELETE CASCADE;
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_2
    FOREIGN KEY (ID_categoria)
    REFERENCES CATEGORIA (ID)
    ON DELETE CASCADE;
 
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_2
    FOREIGN KEY (ID_mercado)
    REFERENCES MERCADO (ID)
    ON DELETE RESTRICT;
 
ALTER TABLE ITEM ADD CONSTRAINT FK_ITEM_3
    FOREIGN KEY (ID_produto)
    REFERENCES PRODUTO (ID)
    ON DELETE RESTRICT;
 
ALTER TABLE compra_item ADD CONSTRAINT FK_compra_item_1
    FOREIGN KEY (ID_item)
    REFERENCES ITEM (ID)
    ON DELETE RESTRICT;
 
ALTER TABLE compra_item ADD CONSTRAINT FK_compra_item_2
    FOREIGN KEY (ID_compra)
    REFERENCES COMPRA (ID)
    ON DELETE SET NULL;